
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hands-on
  name: hands-on
  namespace: user-14
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hands-on
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hands-on
        environment: prod
        version: 1.0.0
    spec:
      containers:
      - image: nginx:latest
        name: foobar
        env:
        - name: DB_HOST
          value: "192.168.0.1"
        - name: DB_NAME
          value: "foobar"
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
            httpHeaders:
            - name: kubelet-probe
              value: "true"
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3